### ISSUE TITLE
More detailed "Development Guide" Recommendations

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#267]
Add comments here to change or extend the caMicroscope development guide section of the README.

**Comment by AbdulRashidReshamwala** [comment]
Add how to setup for development
```
  viewer:
    build: "../caMicroscope"
    container_name: ca-front
    volumes:
      - ./config/login.html:/var/www/html/login.html
      - ../caMicroscope/:/var/www/html/  
```
